
/* -------------------------------------------------------------------
   Code generated by SAS Task

   Generated on: Thursday, January 08, 2015 at 11:11:47 AM
   By task: Data Set Attributes1

   Input Data: Local:MYDATA.FULLYR_2012_FILTER_RESULTS
   Server:  Local
   ------------------------------------------------------------------- */

TITLE "Data Set Attributes for Subset ;
FOOTNOTE;
FOOTNOTE1 "Generated by the SAS System (&_SASSERVERNAME, &SYSSCPL) on %TRIM(%QSYSFUNC(DATE(), NLDATE20.)) at %TRIM(%SYSFUNC(TIME(), TIMEAMPM12.))";

PROC DATASETS NOLIST NODETAILS; 
   CONTENTS DATA=MYDATA.FULLYR_2012_FILTER_RESULTS;

RUN;